### ISSUE TITLE
MT reload Error again

### ISSUE THREAD

**Issue by Dream-Master** [stanhebben/MineTweaker#25]
---

[11/12/2014 17:46:49 PM] [Server thread/ERROR]: Couldn't process command: 'mt reload'
[11/12/2014 17:46:49 PM] java.lang.NullPointerException
[11/12/2014 17:46:49 PM]    at modtweaker.mods.tconstruct.handlers.Smeltery$RemoveMelting.undo(Smeltery.java:187) ~[Smeltery$RemoveMelting.class:?]
[11/12/2014 17:46:49 PM]    at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:83) ~[MTTweaker.class:?]
[11/12/2014 17:46:49 PM]    at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:589) ~[MineTweakerImplementationAPI.class:?]
[11/12/2014 17:46:49 PM]    at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82) ~[MineTweakerImplementationAPI$1.class:?]
[11/12/2014 17:46:49 PM]    at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610) ~[MineTweakerImplementationAPI$19.class:?]
[11/12/2014 17:46:49 PM]    at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124) ~[MCServer$MCCommand.class:?]
[11/12/2014 17:46:49 PM]    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
[11/12/2014 17:46:49 PM]    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
[11/12/2014 17:46:49 PM]    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
[11/12/2014 17:46:49 PM]    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
[11/12/2014 17:46:49 PM]    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
[11/12/2014 17:46:49 PM]    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[11/12/2014 17:46:49 PM]    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[11/12/2014 17:46:49 PM]    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[11/12/2014 17:46:49 PM]    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[11/12/2014 17:46:49 PM]    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
[11/12/2014 17:46:49 PM]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[11/12/2014 17:46:49 PM]    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[11/12/2014 17:46:49 PM] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
[11/12/2014 17:46:55 PM] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiChat
[11/12/2014 17:46:59 PM] [Server thread/ERROR]: Couldn't process command: 'mt reload'
[11/12/2014 17:46:59 PM] java.lang.NullPointerException
[11/12/2014 17:46:59 PM]    at modtweaker.mods.tconstruct.handlers.Smeltery$RemoveMelting.undo(Smeltery.java:187) ~[Smeltery$RemoveMelting.class:?]
[11/12/2014 17:46:59 PM]    at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:83) ~[MTTweaker.class:?]
[11/12/2014 17:46:59 PM]    at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:589) ~[MineTweakerImplementationAPI.class:?]
[11/12/2014 17:46:59 PM]    at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82) ~[MineTweakerImplementationAPI$1.class:?]
[11/12/2014 17:46:59 PM]    at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610) ~[MineTweakerImplementationAPI$19.class:?]
[11/12/2014 17:46:59 PM]    at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124) ~[MCServer$MCCommand.class:?]
[11/12/2014 17:46:59 PM]    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
[11/12/2014 17:46:59 PM]    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
[11/12/2014 17:46:59 PM]    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
[11/12/2014 17:46:59 PM]    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
[11/12/2014 17:46:59 PM]    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
[11/12/2014 17:46:59 PM]    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[11/12/2014 17:46:59 PM]    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[11/12/2014 17:46:59 PM]    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[11/12/2014 17:46:59 PM]    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[11/12/2014 17:46:59 PM]    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
[11/12/2014 17:46:59 PM]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[11/12/2014 17:46:59 PM]    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[11/12/2014 17:46:59 PM] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

**Comment by Dream-Master** [comment]
I see it is a Modtweaker Issue

**Comment by Dream-Master** [comment]
I Think i find the error. i have to using not Ore dict entries in the remove melt recipes.
